name: Project submission template

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Fill in this template to submit a project

labels: ["project"]

# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        ## Guidelines

        We are very excited to meet you at [Brainhack School](https://school-brainhack.github.io/) 🎉.

        To submit a project:

        - you should be a student registered with one of the [Brainhack School hubs](https://school-brainhack.github.io/locations/). 

        - make sure you have read our [Student Guidelines]( )

        - fill in all the required items (marked with a red asterisk `*`) in the form below. 

        - click on `Submit new issue` at the bottom of the form

  # ----------------------------------------------------------------------------
  # PROJECT INFO
  # ----------------------------------------------------------------------------

  - type: markdown
    attributes:
      value: |
        ## Project info

  # ----------------------------------------------------------------------------
  # required
  # ----------------------------------------------------------------------------

  - type: textarea
    attributes:
      label: Title
      description: Add a title to describe your project.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Leaders
      description: Add the full name of the project leader.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Collaborators
      description: List the full names of any person contributing to the project.
      placeholder: Please add collaborators within your proposed project
    validations:
      required: false

  - type: dropdown
    attributes:
      description: Brainhack School Hub event you registered for. Several options are possible.
      label: Brainhack School 2023 Hub
      multiple: true
      options:
        - Marburg
        - Paris
        - Taiwan
        - Humai
        - Uruguay
        - UdeM
        - Polytechnique
        - Toronto

    validations:
      required: true

  - type: textarea
    attributes:
      label: Project Description
      description: Add a brief description of the project.

        Try to include all the relevant information to answer the following
        questions.
      value: |
        - Share a short background of your project.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Link to project repository/sources
      description:
        "If your project already exists, please provide a link to project
        repository/sources (e.g., Github link)"
      placeholder: https://github.com/user_name/my_awesome_project
    validations:
      required: true

  - type: textarea
    attributes:
      label: Goals for the Project
      description: Add a list of milestones or deliverables that you expect to
        achieve during the event.

        Try to provide goals of varying complexity for contributors with
        different sets of skills
    validations:
      required: true

  - type: textarea
    attributes:
      label: Deliverables
      description: Add a list of deliverables you aim to obtain with this project.

    validations:
      required: true

  - type: textarea
    attributes:
      label: Skills
      description: Add a list of skills you aim to gain with this project.

        Try to think of both coding and non-coding skills.

      placeholder: |
        - Python: advanced
        - FSL: basics
    validations:
      required: true

  - type: textarea
    attributes:
      label: Data to use
      description:
        If your project uses data, add a short description of the data and a
        link to its source.
    validations:
      required: false

  # ----------------------------------------------------------------------------
  # LABELS
  # ----------------------------------------------------------------------------

  - type: markdown
    attributes:
      value: |
        ## Project labels

        These labels can help match your project with the attendees' interests.

  - type: dropdown
    attributes:
      label: Type
      multiple: true
      options:
        - coding_methods
        - data_management
        - documentation
        - method_development
        - pipeline_development
        - tutorial_recording
        - visualization
        - other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Development status
      multiple: false
      options:
        - 0_concept_no_content
        - 1_basic structure
        - 2_releases_existing
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Topic
      multiple: true
      options:
        - bayesian_approaches
        - causality
        - connectome
        - data_visualisation
        - deep_learning
        - diffusion
        - diversity_inclusivity_equality
        - EEG_EventRelatedResponseModelling
        - EEG_source_modelling
        - Granger_causality
        - hypothesis_testing
        - ICA
        - information_theory
        - machine_learning
        - MR_methodologies
        - neural_decoding
        - neural_encoding
        - neural_networks
        - PCA
        - physiology
        - reinforcement_learning
        - reproducible_scientific_methods
        - single_neuron_models
        - statistical_modelling
        - systems_neuroscience
        - tractography
        - other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Tools
      multiple: true
      options:
        - AFNI
        - ANTs
        - BIDS
        - Brainstorm
        - CPAC
        - Datalad
        - DIPY
        - FieldTrip
        - fMRIPrep
        - Freesurfer
        - FSL
        - Jupyter
        - MNE
        - MRtrix
        - Nipype
        - NWB
        - SPM
        - other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Programming language
      multiple: true
      options:
        - C++
        - containerization
        - documentation
        - Java
        - Julia
        - Matlab
        - Python
        - "`R`"
        - shell_scripting
        - unix_command_line
        - html_css
        - javascript
        - other
        - not_applicable
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Modalities
      multiple: true
      options:
        - behavioral
        - DWI
        - ECG
        - ECOG
        - EEG
        - eye_tracking
        - fMRI
        - fNIRS
        - MEG
        - MRI
        - PET
        - TDCS
        - TMS
        - other
        - not_applicable
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description:
        Ticked the `other` option on one of the menu above and want to add
        details? Any extra label we did not cover? Some softwares you are using
        we forgot to mention? Please use the space if there is anything else
        that you would like to add about your project.
    validations:
      required: false
